question_1="what is the function used to display text in phyton ?"
answer_1=" function that used to display text in phyton is print function If we don't use print then we won't be able to display anything on the screen in any other way"
question_2="In Python, which data type is used to store a whole number?"
answer_2="Integer because it allows us to store a whole number as a number rather than a string or a decimal."
question_3="Which of the following data types is used to store text in Python?"
answer_3="Text is stored in Python as a string, we can make anything into a string"
question_4=" What is the result of the expression 10 + 5*2 in Python?"
answer_4="The answer is 20 because multiplication is done first and then addition"
question_5="Which of the following is the correct way to assign the value 42 to a variable named answer in Phyton ?"
answer_5="The answer is answer=42 because in the question we were asked about a variable named answer and not a variable named 42"
question_6="What is the process of identifying and fixing errors in a program called?"
answer_6="The answer is debugging because the stage of writing the code when the written code is checked with the programming dictionary is called debugging"
question_7="Which is commonly used in Python for naming variables and functions, where words are separated  by udenscores "